removed (apparently) unused code that does no longer compile with the Microsoft compiler:
src\modules\kernel\bat5.mx(1036) : error C2220: warning treated as error - no "object" file generated
src\modules\kernel\bat5.mx(1036) : warning C4244: "=" : conversion from "lng" to "wrd", possible loss of data