Get rid of a nasty form of cheating by the server, and survive it properly, instead of locking up.  If the server sends tuplecount 48, but sends a prompt after 5 rows, we now are able to detect and balk on this.
% JdbcClient
Welcome to the MonetDB interactive JDBC terminal!
Database: MonetDB 4.5.0
Driver: MonetDB Native Driver 1.0 (Dawn+)
Type \q to quit, \h for a list of available commands
auto commit mode: on
monetdb-> select * from allnewtriples;
Error: Inconsistent state detected!  Current block capacity: 48, block
usage: 5.  Did MonetDB sent what it promised to send?

+------------+------------+------------+------------+----------+
| id         | subject    | predicate  | object     | explicit |
+============+============+============+============+==========+
monetdb-> \q