profiler.c: ensure variables are initialized before being used
fixing optimized compilation with gcc:

.../MonetDB/clients/mapiclient/../R/MonetDB.R/src/profiler.c: In function ?profiler_thread?:
.../MonetDB/clients/mapiclient/../R/MonetDB.R/src/profiler.c:219:59: error: ?profiler_querystart? may be used uninitialized in this function [-Werror=maybe-uninitialized]
          if (profiler_msgs_expect > 0 && (profiler_tsms() - profiler_querystart) > 500) {
                                                           ^