fixed LENFMT for SQLLEN on 64-bit: SQLLEN appears to be typedef long (not typedef long long); hence, LENFMT should be "%ld" (not "%lld")
found be clang 2.8 on 64-bit Fedora 14:
clients/src/odbc/driver/SQLBindCol.c:55:6: error: conversion specifies type 'long long' but the argument has type 'SQLLEN' (aka 'long') [-Wformat]
        ODBCLOG("SQLBindCol " PTRFMT " %d %d " LENFMT "\n", PTRFMTCAST hStmt, nCol, nTargetType, nTargetValueMax);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/export/scratch0/manegold/MonetDB/HG/Oct2010/source/clients/src/odbc/driver/SQLBindCol.c:55:45: note: instantiated from:
        ODBCLOG("SQLBindCol " PTRFMT " %d %d " LENFMT "\n", PTRFMTCAST hStmt, nCol, nTargetType, nTargetValueMax);
                                               ^                                                 ~~~~~~~~~~~~~~~
In file included from /export/scratch0/manegold/MonetDB/HG/Oct2010/source/clients/src/odbc/driver/SQLBindCol.c:39:
/export/scratch0/manegold/MonetDB/HG/Oct2010/source/clients/src/odbc/driver/ODBCGlobal.h:151:21: note: instantiated from:
#define LENFMT          "%lld"
                         ~~~^
1 error generated.