We must define YYMALLOC and YYFREE at least on Windows when using bison 2.4.1 or else we get: y.tab.c(381): error #1736: dllexport/dllimport conflict with "malloc" (declared at line 601 of "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdlib.h"); dllimport/dllexport dropped   void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */         ^
y.tab.c(388): error #1736: dllexport/dllimport conflict with "free" (declared at line 600 of "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdlib.h"); dllimport/dllexport dropped
  void free (void *); /* INFRINGES ON USER NAME SPACE */
       ^
compilation aborted for monet_parse.tab.c (code 2)

And then we might as well define them to GDK{malloc,free}.