Backing out changeset 5c511d5ec062:
Not using "-n" with php on Windows results in a segfault,
and thus does not help to avoid
Fatal error: Call to undefined function socket_create() in ...\install\share\php\monetdb\php_mapi.inc on line 636